// Generated by CoffeeScript 1.9.3
(function() {
  var config, conn, mysql;

  mysql = require("mysql");

  config = require('../config');

  conn = mysql.createConnection({
    host: config.DB_HOST,
    user: config.DB_USER,
    password: config.DB_PASSWORD,
    database: config.DB_NAME,
    port: 3306
  });

  module.exports = conn;

}).call(this);
